# Kryptografia - Baby Kyber

## Pierścień $\mathbb{Z}_n$

In [1]:
class Zn():
    def __init__(self,num,N):
        self.N=N
        self.num=num%self.N

    def __str__(self):
        return str(self.num)

    def __add__(self,other):
        if isinstance(other,Zn):
            if self.N==other.N:
                return Zn(self.num+other.num,self.N)
            else:
                raise ValueError('Not compatible mod rings')
        elif isinstance(other,int):
            return Zn(self.num+other,self.N)
        else:
            raise TypeError(f"unsupported operand type(s) for +: 'Zn' and '{type(other).__name__}'")


    def __radd__(self,other):
        if isinstance(other,int):
            return Zn(self.num+other,self.N)
        else:
            raise TypeError(f"unsupported operand type(s) for +: '{type(other).__name__}' and 'Zn'")


    def __mul__(self,other):
        if isinstance(other,Zn):
            if self.N==other.N:
                return Zn(self.num*other.num,self.N)
            else:
                raise ValueError('Not compatible mod rings')
        elif isinstance(other,int):
            return Zn(self.num*other,self.N)
        else:
            raise TypeError(f"unsupported operand type(s) for *: 'Zn' and '{type(other).__name__}'")

    def __rmul__(self,other):
        if isinstance(other,int):
            return Zn(self.num*other,self.N)
        else:
            raise TypeError(f"unsupported operand type(s) for *: '{type(other).__name__}' and 'Zn'")

    def __sub__(self,other):
        if isinstance(other,Zn):
            if self.N==other.N:
                return Zn(self.num-other.num,self.N)
            else:
                raise ValueError('Not compatible mod rings')
        elif isinstance(other,int):
            return Zn(self.num-other,self.N)
        else:
            raise TypeError(f"unsupported operand type(s) for -: 'Zn' and '{type(other).__name__}'")


    def __rsub__(self,other):
        if isinstance(other,int):
            return Zn(other-self.num,self.N)
        else:
            raise TypeError(f"unsupported operand type(s) for -: '{type(other).__name__}' and 'Zn'")

    def __pow__(self,other):
        if isinstance(other,Zn):
            if self.N==other.N:
                return Zn(pow(self.num,other.num,self.N),self.N)
            else:
                raise ValueError('Not compatible mod rings')
        elif isinstance(other,int):
            return Zn(pow(self.num,other,self.N),self.N)
        else:
            raise TypeError(f"unsupported operand type(s) for **: 'Zn' and '{type(other).__name__}'")


    def __rpow__(self,other):
        if isinstance(other,int):
            return Zn(pow(other,self.num,self.N),self.N)
        else:
            raise TypeError(f"unsupported operand type(s) for **: '{type(other).__name__}' and 'Zn'")

    def __repr__(self):
        return str(self.num)

## Pierścień $\mathbb{Z}_{17}[X]/(X^4+1)$

In [13]:
import numpy as np


class Rq():
    q=17
    f=np.array([1,0,0,0,1])
    def __init__(self,vec):
        _,r=np.polydiv(np.array(vec),self.f)
        self.vec=r%17

    def __repr__(self):
        return str(self.vec)

    def __add__(self,other):
        if isinstance(other,Rq):
            return Rq(np.polyadd(self.vec,other.vec))
        else:
            raise TypeError(f"unsupported operand type(s) for +: 'Rq' and '{type(other).__name__}'")

    def __sub__(self,other):
        if isinstance(other,Rq):
            return Rq(np.polyadd(self.vec,-1*other.vec))
        else:
            raise TypeError(f"unsupported operand type(s) for +: 'Rq' and '{type(other).__name__}'")


    def __mul__(self,other):
        if isinstance(other,Rq):
            return Rq(np.polymul(self.vec,other.vec))
        elif isinstance(other,int):
            return Rq(other*self.vec)
        else:
            raise TypeError(f"unsupported operand type(s) for *: 'Rq' and '{type(other).__name__}'")

    __rmul__=__mul__

## Baby Kyber

### Generowanie klucza

$A=\left[\begin{matrix}
    6x^3+16x^2+16x+11&9x^3+4x^2+6x+3\\
    5x^3+3x^2+10x+1&6x^3+x^2+9x+15
\end{matrix}\right]$

$\mathbf{s}=(-x^3-x^2+x,-x^3-x)$

$\mathbf{e}=(x^2,x^2-x)$

$\mathbf{t}=A\mathbf{s}+\mathbf{e}:\ \ \mathbf{t}=(16x^3+15x^2+7,10x^3+12x^2+11x+6)$

In [31]:
A = np.array([
  [Rq([6, 16, 16, 11]), Rq([9, 4, 6, 3 ])],
  [Rq([5, 3,  10, 1 ]), Rq([6, 1, 9, 15])],
])
s = np.array(
  [Rq([-1, -1, 1, 0]), Rq([-1, 0, -1, 0])]
)
e = np.array(
  [Rq([1, 0, 0]), Rq([1, -1, 0])]
)

t = A @ s + e
t

array([[16. 15.  0.  7.], [10. 12. 11.  6.]], dtype=object)

### Szyfrowanie

$m=1\cdot x^3+0\cdot x^2+1\cdot x+1=x^3+x+1$

$\mathbf{r}=(-x^3+x^2,x^3+x^2-1)$

$\mathbf{e_1}=(x^2+x,x^2)$

$e_2=-x^3-x^2$

$\mathbf{u}=A^T\mathbf{r}+\mathbf{e_1}:\ \ \mathbf{u}=(11x^3+11x^2+10x+3,4x^3+4x^2+13x+11)$

$v=\mathbf{t}^T\mathbf{r}+e_2+\lfloor\frac{q}{2}\rceil m:\ \ v=8x^3+6x^2+9x+16$

$\mathbf{c}=(\mathbf{u},v):\ \ \mathbf{c}=((11x^3+11x^2+10x+3,4x^3+4x^2+13x+11),8x^3+6x^2+9x+16)$

In [19]:
from math import ceil


m = Rq([1, 0, 1, 1])
r = np.array(
  [Rq([-1, 1, 0, 0]), Rq([1, 1, 0, -1])]
)
e1 = np.array(
  [Rq([1, 1, 0]), Rq([1, 0, 0])]
)
e2 = Rq([-1, -1, 0, 0])

u = A.T @ r + e1
v = t.T @ r + e2 + ceil(Rq.q / 2) * m

c = (u, v)
c

(array([[11. 11. 10.  3.], [ 4.  4. 13. 11.]], dtype=object),
 [ 8.  6.  9. 16.])

### Deszyfrowanie
$m_n=v-\mathbf{s}^T\mathbf{u}:\ \ m_n=8x^3+14x^2+8x+6$


In [20]:
mn = v - s.T @ u
mn

[ 8. 14.  8.  6.]

In [27]:
def generate_polynomial(degree: int, coefficients: np.ndarray | int = np.array([-1, 0, 1])) -> Rq:
  return Rq(np.random.choice(coefficients, degree))

In [29]:
def benchmark_baby_kaber(k: int, samples: int) -> None:
  for i in range(samples):
    A = np.array([
      [generate_polynomial(k, coefficients=Rq.q) for _ in range(k)]
        for _ in range(k)
    ])
    s = np.array([generate_polynomial()])

[ 0  0  0 -1]


[16. 16.  1. 16.]